color0 #424940
color1 #ffb4ab
color2 #a6d2a3
color3 #baccb5
color4 #98cee8
color5 #a6d2a3
color6 #baccb5
color7 #e2e3dd
color8 #8c9389
color9 #ffb4ab
color10 #a6d2a3
color11 #baccb5
color12 #98cee8
color13 #a6d2a3
color14 #baccb5
color15 #e2e3dd

cursor                #e2e3dd
cursor_text_color     #121411
background            #121411
foreground            #e2e3dd
selection_foreground  #c2c8bd
selection_background  #424940
active_border_color   #a6d2a3
inactive_border_color #424940
url_color             #a6d2a3

active_tab_foreground   #113817
active_tab_background   #a6d2a3
inactive_tab_foreground #c2c8bd
inactive_tab_background #424940
cursor_trail_color      #c2c8bd
